### PR TITLE
Refactor of entire code base

### PR DESCRIPTION
**Pull request by jokesper**
I have rewritten the interface for this library and I have added the additional feature of cloning the armor stand to make a box

.

### CODE REVIEW

**Review by bonsaiiV — COMMENTED** [review]
Many files are missing a newline at EOF

**Comment by jkeDev** [comment]
Thank you for the response I will fix it in my next commit and also add a CONTRIBUTE.md file so other people will also know about those style guides.
What line ending should the files contain LF or CRLF?

**Review by bonsaiiV — CHANGES_REQUESTED** [review]
Why do you use interchunk align? More flexibility would be achieved if the player 16 const scoreboard was a scoreboard intended to be written to before execution.
For example using an x_align scoreboard and setting it to 32 would allow for an interchunk align of 2, or setting it to 8 would allow for an interchunk align of 0.5, which with the proposed implementation would not be possible.

The cloning of the armorstand while possibly practical does not fit the intended scope of the datapack.

**Comment by bonsaiiV** [comment]
> Thank you for the response I will fix it in my next commit and also add a CONTRIBUTE.md file so other people will also know about those style guides. What line ending should the files contain LF or CRLF?

idc just stop github from screaming about it

**Comment by jkeDev** [comment]
Thank you again for the feedback,
I think I will move it to corresponding scoreboards on the armor stand with the default being 16.
I will also move the cloning part as an extension datapack to another repo.

**Comment by jkeDev** [comment]
I have now added the solutions to your feedback. Please review those again.

**Pull request merged**
